// Code generated by ogen, DO NOT EDIT.
package api

type APIAuthPostRes interface {
	aPIAuthPostRes()
}

type APIBuyItemGetRes interface {
	aPIBuyItemGetRes()
}

type APIInfoGetRes interface {
	aPIInfoGetRes()
}

type APISendCoinPostRes interface {
	aPISendCoinPostRes()
}
