// Code generated by ogen, DO NOT EDIT.

package api

// OperationName is the ogen operation name
type OperationName = string

const (
	APIAuthPostOperation     OperationName = "APIAuthPost"
	APIBuyItemGetOperation   OperationName = "APIBuyItemGet"
	APIInfoGetOperation      OperationName = "APIInfoGet"
	APISendCoinPostOperation OperationName = "APISendCoinPost"
)
