// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// APIAuthPost implements POST /api/auth operation.
//
// Аутентификация и получение JWT-токена. При первой
// аутентификации пользователь создается
// автоматически.
//
// POST /api/auth
func (UnimplementedHandler) APIAuthPost(ctx context.Context, req *AuthRequest) (r APIAuthPostRes, _ error) {
	return r, ht.ErrNotImplemented
}

// APIBuyItemGet implements GET /api/buy/{item} operation.
//
// Купить предмет за монеты.
//
// GET /api/buy/{item}
func (UnimplementedHandler) APIBuyItemGet(ctx context.Context, params APIBuyItemGetParams) (r APIBuyItemGetRes, _ error) {
	return r, ht.ErrNotImplemented
}

// APIInfoGet implements GET /api/info operation.
//
// Получить информацию о монетах, инвентаре и истории
// транзакций.
//
// GET /api/info
func (UnimplementedHandler) APIInfoGet(ctx context.Context) (r APIInfoGetRes, _ error) {
	return r, ht.ErrNotImplemented
}

// APISendCoinPost implements POST /api/sendCoin operation.
//
// Отправить монеты другому пользователю.
//
// POST /api/sendCoin
func (UnimplementedHandler) APISendCoinPost(ctx context.Context, req *SendCoinRequest) (r APISendCoinPostRes, _ error) {
	return r, ht.ErrNotImplemented
}
