#package: merch_store_api
#output: generated.go
#generate:
#  - types
#  - client
#  - server
#  - embedded-spec

package: merch_store_api
generate:
  std-http-server: true
  models: true
output: generated.go